default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RailsExe_hs_development


test:
  <<: *default
  database: RailsExe_hs_test

production:
  <<: *default
  database: RailsExe_hs_production
  username: RailsExe_hs
  password: <%= ENV['RAILSEXE_HS_DATABASE_PASSWORD'] %>
